
name: UNet

channels:
  - conda-forge
  - defaults
    
dependencies:
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1
  - pyqt=5.12
  - napari[pyqt5]
  - numpy=1.24.1
  - pandas=1.5.2
  - scipy=1.10.0
  - scikit-image=0.19.3
  - opencv=4.5.5
  - scikit-learn=1.2.0
  - matplotlib-base=3.6.2
  - joblib=1.2.0
  - pip=22.3.1
  - pip:
    - tensorflow-gpu==2.10
